FROM ubuntu
RUN apt-get update
RUN apt-get install -y software-properties-common
RUN add-apt-repository -y ppa:ethereum/ethereum
RUN apt-get update
RUN apt-get -y install ethereum
RUN apt install -y npm
RUN apt-get install -y python-software-properties
RUN apt-get install -y curl
RUN curl -sL https://deb.nodesource.com/setup_6.x | bash -
RUN apt-get install -y nodejs
RUN apt-get update
RUN apt-get install -y git
RUN npm install -y web3
RUN npm install -g -y  truffle@3.2.2
RUN npm install -g -y webpack
RUN npm install -y solc
RUN npm install -g -y ethereumjs-testrpc


RUN truffle init webpack
#RUN rm -f contracts/MetaCoin.sol contracts/ConvertLib.sol;
#COPY . .

#RUN cd /usr/local/dapps/TokenTest; echo -e "window.web3 = new Web3(new Web3.providers.HttpProvider(\"http://$ip:8545\"));\n$(cat ./app/javascripts/app.js)" > ./app/javascripts/app.js

ENTRYPOINT ./doit


# docker build . -t testrpc
# docker run -it testrpc bash

